import React, {useEffect, useState} from 'react';
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {data} from '../util/data'


const inter = Inter({ subsets: ["latin"] });
console.log(data);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous"
        ></link>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <table className="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">name</th>
                <th scope="col">age</th>
                <th scope="col">mail</th>
                <th scope="col">number</th>
                <th scope="col">address</th>
              </tr>
            </thead>
            <tbody>
              {data.map((element) => {
                return (
                  <tr>
                  <th scope="row">{data.indexOf(element + 1)}</th>
                  <td>{element.name}</td>
                  <td>{element.age}</td>
                  <td>{element.mail}</td>
                  <td>{element.number}</td>
                  <td>{element.address}</td>
                </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
